apiVersion: apps/v1
kind: Deployment
metadata:
  name: data-analyzer
  labels:
    app: data-analyzer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: data-analyzer
  template:
    metadata:
      labels:
        app: data-analyzer
    spec:
      containers:
        - name: data-analyzer
          image: data-analyzer:latest
          imagePullPolicy: Never          # use local Minikube Docker image
          ports:
            - containerPort: 8501
          env:
            - name: STREAMLIT_SERVER_HEADLESS
              value: "true"
            - name: STREAMLIT_SERVER_PORT
              value: "8501"
            - name: STREAMLIT_SERVER_ADDRESS
              value: "0.0.0.0"
          resources:
            requests:
              cpu: "250m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
          readinessProbe:
            httpGet:
              path: /_stcore/health
              port: 8501
            initialDelaySeconds: 15
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /_stcore/health
              port: 8501
            initialDelaySeconds: 30
            periodSeconds: 20
